create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','polo_manager','zone_manager','worker','external');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,role public.app_role not null default 'external',polo text,zone text,cpf text,registration text,active boolean not null default true,created_at timestamptz not null default now());
create table public.routes(id uuid primary key default gen_random_uuid(),polo text,zone text,route_code text,municipalities text,urns integer,operation_date date,vehicle text,plate text,driver text,driver_cpf text,driver_phone text,cnh text,supplier text,collaborator text,collaborator_cpf text,collaborator_phone text,situation text not null default 'Aguardando alocação',situation_manual boolean not null default false,driver_registration text,collaborator_registration text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.vehicles(id uuid primary key default gen_random_uuid(),plate text unique not null,model text,brand text,polo text,supplier text,resource_type text,situation text,crlv text,crlv_validity date,created_at timestamptz not null default now());
create table public.drivers(id uuid primary key default gen_random_uuid(),name text not null,registration text,cpf text,phone text,polo text,bond text,situation text,cnh_status text,cnh_number text,category text,cnh_validity date,created_at timestamptz not null default now());
create table public.mission_events(id uuid primary key default gen_random_uuid(),route_id uuid not null references public.routes(id) on delete cascade,event_type text not null check(event_type in('started','stop','completed')),section text,urns_quantity integer check(urns_quantity is null or urns_quantity>=0),created_by uuid not null default auth.uid() references auth.users(id),created_at timestamptz not null default now(),check(event_type<>'stop' or (section is not null and urns_quantity is not null)));
create index routes_polo_idx on public.routes(polo);create index routes_zone_idx on public.routes(zone);create index routes_driver_cpf_idx on public.routes(driver_cpf);create index routes_collab_cpf_idx on public.routes(collaborator_cpf);create index routes_driver_reg_idx on public.routes(driver_registration);create index routes_collab_reg_idx on public.routes(collaborator_registration);create index mission_route_idx on public.mission_events(route_id);
create or replace function public.norm_id(v text) returns text language sql immutable as $$select regexp_replace(coalesce(v,''),'\D','','g')$$;
create or replace function public.my_profile() returns public.profiles language sql stable security definer set search_path=public as $$select * from public.profiles where id=auth.uid()$$;
create or replace function public.can_view_route(r public.routes) returns boolean language plpgsql stable security definer set search_path=public as $$declare p public.profiles;begin select * into p from public.profiles where id=auth.uid() and active; if not found then return false;end if;return case p.role when 'admin' then true when 'polo_manager' then r.polo=p.polo when 'zone_manager' then r.zone=p.zone and (p.polo is null or r.polo=p.polo) when 'worker' then (public.norm_id(r.driver_cpf)=public.norm_id(p.cpf) and public.norm_id(p.cpf)<>'') or (public.norm_id(r.collaborator_cpf)=public.norm_id(p.cpf) and public.norm_id(p.cpf)<>'') or (coalesce(r.driver_registration,'')=coalesce(p.registration,'') and coalesce(p.registration,'')<>'') or (coalesce(r.collaborator_registration,'')=coalesce(p.registration,'') and coalesce(p.registration,'')<>'') else false end;end$$;
create or replace function public.can_manage_route(r public.routes) returns boolean language plpgsql stable security definer set search_path=public as $$declare p public.profiles;begin select * into p from public.profiles where id=auth.uid() and active; if not found then return false;end if;return p.role='admin' or (p.role='polo_manager' and r.polo=p.polo) or (p.role='zone_manager' and r.zone=p.zone and (p.polo is null or r.polo=p.polo));end$$;
create or replace function public.can_operate_route(r public.routes) returns boolean language plpgsql stable security definer set search_path=public as $$declare p public.profiles;begin select * into p from public.profiles where id=auth.uid() and active;if not found then return false;end if;return public.can_manage_route(r) or public.can_view_route(r) and p.role='worker';end$$;
create or replace function public.routes_before_write() returns trigger language plpgsql as $$begin new.updated_at=now();if new.situation_manual=false and nullif(trim(coalesce(new.plate,'')),'') is not null and nullif(trim(coalesce(new.driver,'')),'') is not null and nullif(trim(coalesce(new.driver_phone,'')),'') is not null then new.situation='Concluído';end if;return new;end$$;
create trigger routes_before_write_trg before insert or update on public.routes for each row execute function public.routes_before_write();
create or replace function public.mission_after_insert() returns trigger language plpgsql security definer set search_path=public as $$begin if new.event_type='started' then update public.routes set situation='Em andamento',situation_manual=true where id=new.route_id;elsif new.event_type='completed' then update public.routes set situation='Concluído',situation_manual=true where id=new.route_id;end if;return new;end$$;
create trigger mission_after_insert_trg after insert on public.mission_events for each row execute function public.mission_after_insert();
create or replace function public.new_user_profile() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.new_user_profile();
alter table public.profiles enable row level security;alter table public.routes enable row level security;alter table public.vehicles enable row level security;alter table public.drivers enable row level security;alter table public.mission_events enable row level security;
revoke all on public.profiles,public.routes,public.vehicles,public.drivers,public.mission_events from anon,authenticated;grant select,update on public.profiles to authenticated;grant select,insert,update,delete on public.routes to authenticated;grant select,insert,update,delete on public.vehicles,public.drivers to authenticated;grant select,insert on public.mission_events to authenticated;
create policy profiles_select on public.profiles for select to authenticated using(id=auth.uid() or (select role from public.profiles where id=auth.uid())='admin');
create policy profiles_update on public.profiles for update to authenticated using((select role from public.profiles where id=auth.uid())='admin') with check((select role from public.profiles where id=auth.uid())='admin');
create policy routes_select on public.routes for select to authenticated using(public.can_view_route(routes) or (select role from public.profiles where id=auth.uid())='external');
create policy routes_insert on public.routes for insert to authenticated with check((select role from public.profiles where id=auth.uid())='admin' or ((select role from public.profiles where id=auth.uid())='polo_manager' and polo=(select polo from public.profiles where id=auth.uid())) or ((select role from public.profiles where id=auth.uid())='zone_manager' and zone=(select zone from public.profiles where id=auth.uid())));
create policy routes_update on public.routes for update to authenticated using(public.can_manage_route(routes)) with check(public.can_manage_route(routes));
create policy routes_delete on public.routes for delete to authenticated using(public.can_manage_route(routes));
create policy vehicles_select on public.vehicles for select to authenticated using((select role from public.profiles where id=auth.uid()) in('admin','polo_manager','zone_manager'));
create policy vehicles_write on public.vehicles for all to authenticated using((select role from public.profiles where id=auth.uid())='admin') with check((select role from public.profiles where id=auth.uid())='admin');
create policy drivers_select on public.drivers for select to authenticated using((select role from public.profiles where id=auth.uid()) in('admin','polo_manager','zone_manager'));
create policy drivers_write on public.drivers for all to authenticated using((select role from public.profiles where id=auth.uid())='admin') with check((select role from public.profiles where id=auth.uid())='admin');
create policy events_select on public.mission_events for select to authenticated using(exists(select 1 from public.routes r where r.id=mission_events.route_id and (public.can_view_route(r) or (select role from public.profiles where id=auth.uid()) in('polo_manager','zone_manager','admin'))));
create policy events_insert on public.mission_events for insert to authenticated with check(exists(select 1 from public.routes r where r.id=mission_events.route_id and public.can_operate_route(r)));
-- Após criar seu primeiro usuário no Auth, promova-o uma única vez no SQL Editor:
-- update public.profiles set role='admin', full_name='Administrador' where id='UUID_DO_USUARIO';

-- SISURNAS: CPF/Matrícula são os identificadores funcionais de acesso.
-- O frontend os converte para <identificador>@sisurnas.local apenas para interoperar com Supabase Auth.
-- O CPF administrativo abaixo é promovido automaticamente quando o usuário Auth correspondente for criado.
create unique index if not exists profiles_cpf_unique on public.profiles(public.norm_id(cpf)) where public.norm_id(cpf)<>'';
create unique index if not exists profiles_registration_unique on public.profiles(registration) where coalesce(registration,'')<>'';
create or replace function public.new_user_profile() returns trigger language plpgsql security definer set search_path=public as $$
declare ident text; is_admin boolean;
begin
 ident:=split_part(coalesce(new.email,''),'@',1);
 is_admin:=public.norm_id(ident)='01636486541';
 insert into public.profiles(id,full_name,role,cpf,registration)
 values(new.id,coalesce(new.raw_user_meta_data->>'full_name',case when is_admin then 'Administrador' else ident end),case when is_admin then 'admin'::public.app_role else 'external'::public.app_role end,case when length(public.norm_id(ident))=11 then public.norm_id(ident) else null end,case when length(public.norm_id(ident))<>11 then ident else null end)
 on conflict(id) do update set role=case when is_admin then 'admin'::public.app_role else public.profiles.role end,cpf=case when is_admin then '01636486541' else public.profiles.cpf end;
 return new;
end$$;
